server:
  port: 8081
spring:
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:clay1
    driverClassName: org.h2.Driver
    username: user
    password: password
clay:
  integration-service:
    url: http://localhost:8080/ticker
